export const SAVE_PERSONAL_INFO_ERROR='SAVE_PERSONAL_INFO_ERROR'
export const SAVE_PERSONAL_INFO_SUCCESS='SAVE_PERSONAL_INFO_SUCCESS'
export const SAVE_PERSONAL_INFO_LOADING='SAVE_PERSONAL_INFO_LOADING'
export const SET_LANGUAGE_DETAILS = 'SET_LANGUAGE_DETAILS';
export const SET_EDUCATIONAL_DETAILS = 'SET_EDUCATIONAL_DETAILS';
export const SET_FAMILY_DETAILS = "SET_FAMILY_DETAILS"